// DOM element references

export const elements = {
  unsupported: document.getElementById('unsupported'),
  insecure: document.getElementById('insecure'),
  createBtn: document.getElementById('createBtn'),
  openBtn: document.getElementById('openBtn'),
  reconnectBtn: document.getElementById('reconnectBtn'),
  editBtn: document.getElementById('editBtn'),
  signatureBtn: document.getElementById('signatureBtn'),
  printBtn: document.getElementById('printBtn'),
  monthNav: document.getElementById('monthNav'),
  prevMonth: document.getElementById('prevMonth'),
  nextMonth: document.getElementById('nextMonth'),
  newMonthBtn: document.getElementById('newMonthBtn'),
  monthLabel: document.getElementById('monthLabel'),
  summary: document.getElementById('summary'),
  metaMonth: document.getElementById('metaMonth'),
  metaEmployer: document.getElementById('metaEmployer'),
  metaEmployee: document.getElementById('metaEmployee'),
  table: document.getElementById('attendanceTable'),
  tableBody: document.getElementById('tableBody'),
  totalValue: document.getElementById('totalValue'),
  daySummary: document.getElementById('daySummary'),
  legend: document.getElementById('legend'),
  fileName: document.getElementById('fileName'),
  dochadzkaView: document.getElementById('dochadzkaView'),
  scView: document.getElementById('scView'),
  tabDochadzka: document.getElementById('tabDochadzka'),
  tabSC: document.getElementById('tabSC'),
  signatureBlock: document.getElementById('signatureBlock'),
  signatureImg: document.getElementById('signatureImg'),
  // SC view elements
  tripList: document.getElementById('tripList'),
  tripControls: document.getElementById('tripControls'),
  tripStartDay: document.getElementById('tripStartDay'),
  tripEndDay: document.getElementById('tripEndDay'),
  tripStartTime: document.getElementById('tripStartTime'),
  tripEndTime: document.getElementById('tripEndTime'),
  tripKm: document.getElementById('tripKm'),
  scDocuments: document.getElementById('scDocuments'),
  cestovnyPrikaz: document.getElementById('cestovnyPrikaz'),
  vyuctovanie: document.getElementById('vyuctovanie'),
  // Vacation view elements
  tabVacations: document.getElementById('tabVacations'),
  vacationsView: document.getElementById('vacationsView'),
  vacationList: document.getElementById('vacationList'),
  vacationControls: document.getElementById('vacationControls'),
  vacationStartDay: document.getElementById('vacationStartDay'),
  vacationEndDay: document.getElementById('vacationEndDay'),
  vacationWorkingDays: document.getElementById('vacationWorkingDays'),
  vacationDocuments: document.getElementById('vacationDocuments'),
  vacationRequest: document.getElementById('vacationRequest'),
};
